import { HttpTypes } from "@medusajs/types"
import { Text } from "@medusajs/ui"

type LineItemOptionsProps = {
  variant: HttpTypes.StoreProductVariant | undefined
  "data-testid"?: string
  "data-value"?: HttpTypes.StoreProductVariant
  size?: string
}

const LineItemOptions = ({
  variant,
  "data-testid": dataTestid,
  "data-value": dataValue,
  size = "text-xs",
}: LineItemOptionsProps) => {
  // Hide variant if it's the default autogenerated one
  if (!variant || variant.title?.toLowerCase() === "default variant") {
    return null
  }

  return (
    <Text
      data-testid={dataTestid}
      data-value={dataValue}
      className={`inline-block ${size} text-ui-fg-muted w-full overflow-hidden text-ellipsis`}
    >
      <span className="normal-case">Size:</span> <span className={variant.title && variant.title.length <= 3 ? "uppercase" : ""}>{variant.title}</span>
    </Text>
  )
}

export default LineItemOptions
