import { HttpTypes } from "@medusajs/types"
import { Text } from "@medusajs/ui"

type LineItemOptionsProps = {
  variant: HttpTypes.StoreProductVariant | undefined
  "data-testid"?: string
  "data-value"?: HttpTypes.StoreProductVariant
}

const LineItemOptions = ({
  variant,
  "data-testid": dataTestid,
  "data-value": dataValue,
}: LineItemOptionsProps) => {
  // Hide variant if it's the default autogenerated one
  if (!variant || variant.title?.toLowerCase() === "default variant") {
    return null
  }

  return (
    <Text
      data-testid={dataTestid}
      data-value={dataValue}
      className="inline-block text-xs text-ui-fg-muted w-full overflow-hidden text-ellipsis"
    >
      Size: <span className={variant.title && variant.title.length <= 3 ? "uppercase" : ""}>{variant.title}</span>
    </Text>
  )
}

export default LineItemOptions
